### ISSUE TITLE
Package your themes for the asset library

### ISSUE THREAD

**Issue by akien-mga** [Geequlim/godot-themes#1]
There is now an (alpha) web frontend for Godot 2.1's asset library, which lets user submit their contents for easier installation directly in Godot: https://godotengine.org/asset-library/frontend/asset

Maybe your themes could be packaged there too?

Don't hesitate to discuss here / on IRC if you're unsure about the process (currently not documented) or if the current system is not fitting for distributing themes.

CC @bojidar-bg

**Comment by akien-mga** [comment]
BTW you could probably drop the `engine.cfg` and `icon.png` files from this repo, I guess they're not needed for the themes?

**Comment by Geequlim** [comment]
Thanks for your suggestions. 
I would submit the themes to the asset library onece the stuff is finished.

**Comment by Geequlim** [comment]
I have submitted the new theme to Godot 2.1's asset library :)
Is any problem with the theme?

**Comment by akien-mga** [comment]
Thanks, I accepted the last edit.

**Comment by akien-mga** [comment]
The theme looks really gorgeous on the screenshots :D

**Comment by akien-mga** [comment]
What happened to your white theme btw? :)

**Comment by Geequlim** [comment]
Most of the default icons are fit for dark themes but not for white themes.
I have discussed this problem with @djrm [here](https://github.com/djrm/godot-design/issues/5#issuecomment-245310641)

There are too much works to do for light themes.

**Comment by Geequlim** [comment]
@akien-mga The white theme is almost done with tinted icons.
But the issue [#6430](https://github.com/godotengine/godot/issues/6430) is more obviously with this theme.
![](https://cdn.rawgit.com/Geequlim/depot/master/images/godot/arc_light_HiDPI.png)
