### ISSUE TITLE
Could you do a version that is like the current default one, but dark gray (see Photoshop for reference)?

### ISSUE THREAD

**Issue by PLyczkowski** [Geequlim/godot-themes#13]

**Comment by Geequlim** [comment]
I will continue fix details for the Arc themes.
The theme editor in godot is not good enough to make a theme to fit all DPIs

**Comment by Geequlim** [comment]
Is this one ok?
![](https://cdn.rawgit.com/Geequlim/depot/master/images/godot/godot%20adobe%20theme%402x.png)

**Comment by PLyczkowski** [comment]
Nope, I was hoping for one that is the same as current official, just desaturated to darkish grey (keeping all the shading and fonts). 

This one was close, still has a bit of the purple color in it though: https://dl.dropboxusercontent.com/s/ky2spr2087h7ima/shot_161218_164529.png 

It one replaced the current one for a while in the repository, but sadly it was reverted.
