### ISSUE TITLE
Theme only works for one project

### ISSUE THREAD

**Issue by toger5** [Geequlim/godot-themes#6]
I installed  your theme (on windows)
(cloned repo -> run the install.py file -> started godot -> changed settings to the ark theme)

I had the same issue @MarianoGnu mentioned in this issue: https://github.com/godotengine/godot/issues/2207

![](https://camo.githubusercontent.com/c815267e2c077e01174ad8ccd3b07c8b38d9da30/68747470733a2f2f692e6779617a6f2e636f6d2f66363762323461396634626438346333353039356436653232313162363464322e706e67)

The theme is shown without any custom resources.
But it works when copy the addons folder with both themes into one of my projects and than choose one of your themes as the editor theme. (but it only works for this one projects...)
If you have na idea i would be very happy.

**Comment by Geequlim** [comment]
## you should set theme to installed file  in . godot/theme/*/*.tres not the one in this project.

Edited.

**Comment by toger5** [comment]
I did. But than i get the theme without the resources.

**Comment by Geequlim** [comment]
which theme you applied?

**Comment by Geequlim** [comment]
Maybe I should get a Windows PC for testing ~

**Comment by toger5** [comment]
I used the ark dark theme. Inside the Godot folder (in windows it is called Godot folder, but it has the same files i have on my mac in the .godot folder ...)

**Comment by Geequlim** [comment]
Maybe the install script generated pathes in tres files use `\` as path separator on Windows. But Godot always use `/`

**Comment by toger5** [comment]
oh this might be the case.
I just checked the files and this is the path the script generates:
"C:\Users\rok\AppData/Roaming/Godot/theme/arc_dark/resources/button/button-insensitive.tres"
I try to fix it if you have an idea how tell me.

Oh i forgot to mention. I also installed it on my mac and it works fine.

**Comment by Geequlim** [comment]
Just pull a pr if you fix that :)

**Comment by toger5** [comment]
This was the problem. I now changed replaced the backslash...  It works
Thank you for the awesome theme :)
PR is coming soon

**Comment by MarianoGnu** [comment]
problem was that the theme was pointing to the external resources with an absolute path (res:/addons/arc-dark/textures/texture.png) instead of a relative path (,/textures/texture.png) that's why it forced you to install in the same place for every project.
Haven't checked how did you fix it :P

**Comment by Geequlim** [comment]
After installation all of the resource pathes used by the themes are replaced to absolute pathes

**Comment by Geequlim** [comment]
The absolute path meas to the  path of the REAL file system not godot's.

Here is the a part of the installed theme file

```
[gd_resource type="Theme" load_steps=435 format=1]

[ext_resource path="/home/geequlim/.godot/theme/arc_light/resources/button/button-insensitive.tres" type="StyleBox" id=1]
[ext_resource path="/home/geequlim/.godot/theme/arc_light/resources/button/button-hover.tres" type="StyleBox" id=2]
[ext_resource path="/home/geequlim/.godot/theme/arc_light/resources/button/button.tres" type="StyleBox" id=3]
[ext_resource path="/home/geequlim/.godot/theme/arc_light/resources/button/button-active.tres" type="StyleBox" id=4]
```

**Comment by MarianoGnu** [comment]
i never saw the install previously
