### ISSUE TITLE
The launcher has wrong scaling with highDPI

### ISSUE THREAD

**Issue by toger5** [Geequlim/godot-themes#9]
Sorry to make another issue...
I tried the highDPI but the scaling of the fonts is a little bit off:

<img width="1025" alt="screen shot 2016-09-10 at 13 55 07" src="https://cloud.githubusercontent.com/assets/16718859/18413500/72d905e6-775e-11e6-8b51-af7d45573378.png">

Any idea why ?

**Comment by Geequlim** [comment]
Sorry I don't really understand with that

**Comment by Geequlim** [comment]
The reason is that Godot Project Manager doesn't support HiDPI properly.

**Comment by toger5** [comment]
oh yea this might be the reason. So it is not on your site :)
I think you can close.
TY

**Comment by Geequlim** [comment]
@toger5  You can test with [latest commit](https://github.com/godotengine/godot/commit/1bf684cea274db7c58b3f62a77ad4de3980c14dc) of godot
